In [219]:
import pandas as pd
import numpy as np

In [220]:
data=pd.read_csv("Titanic-Dataset.csv")
data.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [221]:
# ismein hum classification use krenge kyon ki ismein hamen outout ko class mien divide krna hai
# hamare pass jaise kai tarah ki classification hai to islie hum ekk ekk krke us rr lagayenge


In [222]:
data.isnull().sum()


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [223]:
data['Age'].fillna(data['Age'].median(), inplace=True)           # is mein hum null values of age ko median ke sath replace krr rhe hai

In [224]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [225]:
# sex= male or female isse hum 0 or 1 ki form mein change krenge 
# ise krne ke lie hum feature scalng nhi label encoding krenge

In [226]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder() # Conversion of Categorical values into Numerical values
data['Sex'] = labelencoder.fit_transform(data['Sex'])

data.head()
# male=1

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [227]:
# data['Age'].fillna(data['Age'].median(), inplace=True)

In [228]:
feature=data[['Sex','Age','SibSp','Fare']].values
target=data['Survived'].values

In [229]:
print(feature)

[[ 1.     22.      1.      7.25  ]
 [ 0.     38.      1.     71.2833]
 [ 0.     26.      0.      7.925 ]
 ...
 [ 0.     28.      1.     23.45  ]
 [ 1.     26.      0.     30.    ]
 [ 1.     32.      0.      7.75  ]]


In [230]:
data['Age'].fillna(data['Age'].median(), inplace=True)

In [231]:
# x=data.iloc[:,1:2].values
# y=data.iloc[:,0:1].values


In [232]:
# print(y)

In [233]:
from sklearn.model_selection import train_test_split

In [234]:
xtrain,xtest,ytrain,ytest=train_test_split(feature,target,train_size=0.8)

In [235]:
print(xtrain)

[[ 1.     36.      0.     12.875 ]
 [ 0.     22.      0.      7.75  ]
 [ 1.     30.      0.      7.25  ]
 ...
 [ 0.      0.75    2.     19.2583]
 [ 0.     56.      0.     83.1583]
 [ 0.     32.      0.     76.2917]]


In [236]:
print(ytrain)

[0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 1
 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 1
 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0
 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1
 1 1 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0
 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1
 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 1 0 1 0 1 0
 1 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1
 1 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0
 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 1 0
 1 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 0 1 0
 0 1 1 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 1 0 0 1
 0 1 1 1 0 0 0 0 0 0 0 0 

In [237]:
print(ytest)

[0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1
 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0
 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1
 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1]


In [238]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

LogisticRegression()

In [239]:
pr=lr.predict(xtest)
print(pr)

[0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0
 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0
 1 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0
 1 1 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 0 0]


In [240]:
print(ytest)

[0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1
 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0
 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1
 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1]


In [241]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(pr,ytest)
print(acc)

0.7262569832402235


In [242]:
# aroun 80 % accuracy aii hai

In [243]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [244]:
predict=rf.predict(xtest)

In [245]:
scd=accuracy_score(ytest,predict)
print(scd)

0.7653631284916201


In [246]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier()
kn.fit(xtrain,ytrain)

KNeighborsClassifier()

In [247]:
pred=kn.predict(xtest)

In [248]:
ac=accuracy_score(ytest,pred)
print(ac)

0.6368715083798883


In [249]:
from sklearn.svm import SVC
s=SVC()
s.fit(xtrain,ytrain)

SVC()

In [250]:
pre1=s.predict(xtest)

In [251]:
acc1=accuracy_score(ytest,pre1)
print(acc1)

0.6424581005586593


In [252]:
# humne randomforst wali algo ko accept kiya hai kyon ki uski accuracy jeada hai

In [253]:
print(predict)

[0 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0
 0 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0
 1 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0]


In [254]:
ans=[[ 1,      23,       0,      15.0458]]
pred1=rf.predict(ans)
print(pred1)

[0]


In [255]:
if pred1==1:
    print("survived")
else:
    print("not survived")

not survived


In [256]:
# abb humne split rr liya hai abb hum isse train krenge data ko

In [257]:
# kneighour lagane ke lie uis mein hame data ko numeric mein ocnvert krna padega pehle then age chalega

In [258]:
# feature scaling krni padegi yahan prr pehle hame the age chalega

In [259]:
# from sklearn.neighbors import KNeighborsClassifiere
# sv=KNeighborsClassifiere()
# sv.fit(xtrain,ytrain)